FROM postgres:latest

# Define o diretório de trabalho dentro do container
WORKDIR /var/lib/postgresql/data

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432

# Comando para iniciar o PostgreSQL
CMD ["postgres"]