spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://${DATABASE_PUBLIC_URL}
        #url: jdbc:h2:mem:db
        username: ${POSTGRESS_USER:postgres}
        password: ${POSTGRESS_PASSWORD:postgres}

    servlet:
        multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB
api:
 security:
    token:
        secret: ${JWT_SECRET:my-secret-key}

minio:
    config:
        url: ${MINIO_URL:http://localhost:9000}
        username: ${MINIO_USERNAME:ROOTUSER}
        password: ${MINIO_PASSWORD:CHANGEME123}

user:
    mock:
        username: admin
        password: admin
    