spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://${DATABASE_PUBLIC_URL}
        #url: jdbc:postgresql://localhost:5432/db
        #url: jdbc:h2:mem:db
        username: ${POSTGRESS_USER:admin}
        password: ${POSTGRESS_PASSWORD:admin}

    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB
api:
 security:
    token:
        secret: ${JWT_SECRET:my-secret-key}

minio:
    config:
        url: ${MINIO_URL:http://localhost:9000}
        username: ${MINIO_USERNAME:ROOTUSER}
        password: ${MINIO_PASSWORD:CHANGEME123}

user:
    mock:
        username: admin
        password: admin

server:
    port: 8080